# Generated by Django 5.0.2 on 2024-02-20 06:05

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_content_file_image_text_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.Orderfield(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=courses.fields.Orderfield(blank=True, default=0),
            preserve_default=False,
        ),
    ]
