# Generated by Django 5.0.2 on 2024-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="overview",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
